config/routes.rb
Rails.application.routes.draw do
  resources :tickets

  root 'tickets#index'
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create 
    temp_ticket_params = ticket_params
    temp_ticket_params[:date_submitted] ? temp_ticket_params[:date_submitted] = temp_ticket_params[:date_submitted].to_s() : nil
    temp_ticket_params[:date_occurred] ? temp_ticket_params[:date_occurred] = temp_ticket_params[:date_occurred].to_s() : nil

    @ticket = Ticket.new(temp_ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    temp_ticket_params = ticket_params
    temp_ticket_params[:date_submitted].present? ? temp_ticket_params[:date_submitted] = temp_ticket_params[:date_submitted].to_s() : nil
    temp_ticket_params[:date_occurred] ? temp_ticket_params[:date_occurred] = temp_ticket_params[:date_occurred].to_s() : nil
    temp_ticket_params[:date_resolved] ? temp_ticket_params[:date_resolved] = temp_ticket_params[:date_resolved].to_s() : nil
    
    respond_to do |format|
      if @ticket.update(temp_ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:date_submitted, :date_occurred, :affected_user, :problem_description, :date_resolved, :problem_resolution)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IT Ticket Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">BWC IT Support</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/tickets/_form.html.erb
<%= simple_form_for @ticket do |f| %>
  <%= f.error_notification %>
  <div class="col-md-6">
    <%= f.input :date_submitted, :as => :hidden, input_html: { value: Time.now } %>
    <%= f.input :date_occurred, :label => false, :as => :datetime_picker, :placeholder => "Date problem started" %>
    <%= f.input :affected_user, :label => false, :placeholder => "Affected user" %>
    <%= f.input :problem_description, :label => false, :placeholder => "Description of the problem" %>
    
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<div class="container well">
	<h1>Editing Ticket</h1>

	<%= simple_form_for @ticket do |f| %>
	  <%= f.error_notification %>
	  <div class="col-md-6">
	    <%= f.input :date_submitted, :as => :datetime_picker %>
	    <%= f.input :date_occurred, :as => :datetime_picker %>
	    <%= f.input :affected_user %>
	    <%= f.input :problem_description %>
	    <%= f.input :date_resolved, :as => :datetime_picker %>
	    <%= f.input :problem_resolution %>
	    
	    <%= f.button :submit %>
	  </div>
	<% end %>
</div>

app/views/tickets/index.html.erb
<div class="container well">
  <h1>All Trouble Tickets</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date submitted</th>
        <th>Date occurred</th>
        <th>Affected user</th>
        <th>Date resolved</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.order("date_submitted").each do |ticket| %>
        <% if ticket.date_resolved.present? %>
          <tr class="success">
        <% else %>
          <tr class="danger">
        <% end %>
          <td><%= ticket.date_submitted.try(:strftime, "%a, %b %d %Y %l:%M %p") %></td>
          <td><%= ticket.date_occurred.try(:strftime, "%a, %b %d %Y %l:%M %p") %></td>
          <td><%= ticket.affected_user %></td>
          <td><%= ticket.date_resolved.try(:strftime, "%a, %b %d %Y %l:%M %p") %></td>
          <td><%= link_to 'Show', ticket, :class => 'btn btn-sm btn-default' %></td>
          <td><%= link_to 'Edit', edit_ticket_path(ticket), :class => 'btn btn-sm btn-default' %></td>
          <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'hidden btn btn-sm btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Ticket', new_ticket_path, :class => "btn btn-default" %>
</div>

app/views/tickets/new.html.erb
<div class="container well">
	<h1>New Trouble Ticket</h1>
	<%= render 'form' %>
</div>

app/views/tickets/show.html.erb
<p>Date Submitted: <%= @ticket.date_submitted %></p>
<p>Date Occurred: <%= @ticket.date_occurred %></p>
<p>Affected User: <%= @ticket.affected_user %></p>
<p>Problem Description: <%= @ticket.problem_description %></p>
<p>Date Resolved: <%= @ticket.date_resolved %></p>
<p>Problem Resolution: <%= @ticket.problem_resolution %></p>

<%= link_to 'Back', tickets_path, :class => "btn btn-default" %>